default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] || `whoami`.chomp %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drugbank_development

test:
  <<: *default
  database: drugbank_test
